CC=gcc
CFLAGS=-g -std=c99 -Wall
#LDFLAGS=-lm

test3:
	./part3 "only one parameter"
	./part3 "biggest parameter" "at" "start"
	./part3 "biggest" "parameter" "at" "end" "very very very big parameter"
	./part3 "answer" "somewhere" "in" "the" "middle"
	./part3 "two" "strings" "the" "same" "length" "ha ha !"

test4:
	./part4 10
	./part4 -f -298
	./part4 -c -12312
	./part4 -f 2312
	./part4 -c 1
